### ISSUE TITLE
Error after upgrading to Next 9 

### ISSUE THREAD

**Issue by adamsoffer** [thundermiracle/next-mui-helper#26]
Hey @thundermiracle - heads up I'm getting an error after upgrading to Next 9. Not exactly sure why!
`Class constructor Document cannot be invoked without 'new'` 

https://codesandbox.io/s/simple-xe67c

**Comment by thundermiracle** [comment]
@adamsoffer 
Thank you for the report! I'll check it soon.

**Comment by thundermiracle** [comment]
It seems that high-order-components are not working in next9.
I need some time to read the next9's source code to figure it out...

**Comment by thundermiracle** [comment]
The error occurred because es6(next9) trys to extend es5(next-mui-helper/makeXXX).
I don't know how to solve this problem right now, but the temporary solution is using next-mui-helper/es6 version as [this example](https://github.com/thundermiracle/next-mui-helper/tree/master/examples/es6) does.

[next.js issue](https://github.com/zeit/next.js/issues/8173)

**Comment by adamsoffer** [comment]
ok thanks @thundermiracle !

**Comment by thundermiracle** [comment]
[next.js issue2](https://github.com/zeit/next.js/issues/8201)

**Comment by thundermiracle** [comment]
@adamsoffer 
I updated the readme right now.
https://github.com/thundermiracle/next-mui-helper#steps-from-next900

The only way to solve this problem is using ES6 modules.
I'm going to close this issue. Feel free to re-open it if you have any problem.
